[toolchain]
anchor_version = "0.32.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
kage = "PRDZsFBacoRGLW5bBumh4Wi42hv8N72akYcWhDgvt9s"

[programs.devnet]
kage = "PRDZsFBacoRGLW5bBumh4Wi42hv8N72akYcWhDgvt9s"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run test"

[test]
startup_wait = 5000

[test.validator]
url = "https://api.devnet.solana.com"
