[toolchain]
anchor_version = "0.32.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
kage = "ASK5m43oRE67ipfwuBbagVaiMQpFKYRTZNsvZXUfBtRp"

[programs.devnet]
kage = "ASK5m43oRE67ipfwuBbagVaiMQpFKYRTZNsvZXUfBtRp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "devnet-new-wallet.json"

[scripts]
test = "pnpm run test"

[test]
startup_wait = 5000

[test.validator]
url = "https://api.devnet.solana.com"
